"""initial schema

Revision ID: 61d7783ed9a5
Revises: 
Create Date: 2026-06-28 07:17:22.383172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d7783ed9a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hygiene_checklists', schema=None) as batch_op:
        batch_op.create_index('ix_hygiene_restaurant_date', ['restaurant_id', 'date'], unique=False)
        batch_op.create_index('ix_hygiene_type', ['checklist_type'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_orders_restaurant_id', ['restaurant_id'], unique=False)
        batch_op.create_index('ix_orders_status', ['status'], unique=False)

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_index('ix_restaurants_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('ix_restaurants_safety_score', ['safety_score'], unique=False)

    with op.batch_alter_table('staff_training', schema=None) as batch_op:
        batch_op.create_index('ix_training_restaurant_id', ['restaurant_id'], unique=False)
        batch_op.create_index('ix_training_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_training', schema=None) as batch_op:
        batch_op.drop_index('ix_training_status')
        batch_op.drop_index('ix_training_restaurant_id')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurants_safety_score')
        batch_op.drop_index('ix_restaurants_owner_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status')
        batch_op.drop_index('ix_orders_restaurant_id')
        batch_op.drop_index('ix_orders_created_at')

    with op.batch_alter_table('hygiene_checklists', schema=None) as batch_op:
        batch_op.drop_index('ix_hygiene_type')
        batch_op.drop_index('ix_hygiene_restaurant_date')

    # ### end Alembic commands ###
